// GENERATED by scripts/build-tokens.mjs from brand/tokens.json. Do not edit by hand.
export const BREAKPOINTS = {
  "xs": "375px",
  "sm": "390px",
  "md": "430px",
  "tablet": "768px",
  "laptop": "1024px",
  "desktop": "1280px",
  "wide": "1440px"
} as const;

export type Breakpoint = keyof typeof BREAKPOINTS;

export const bpPx = (b: Breakpoint): number => parseInt(BREAKPOINTS[b], 10);
