# Generated by Django 5.2.17 on 2026-08-05 18:14

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        default=store.models.generate_public_id,
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Ожидает оплаты"),
                            ("pending_review", "Чек на проверке"),
                            ("issuing", "Выдаём eSIM…"),
                            ("issued", "eSIM выдан"),
                            ("rejected", "Оплата отклонена"),
                            ("failed", "Ошибка выдачи"),
                        ],
                        default="pending_payment",
                        max_length=24,
                    ),
                ),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone", models.CharField(max_length=32)),
                ("phone_verified", models.BooleanField(default=False)),
                ("plan_id", models.CharField(max_length=64)),
                ("plan_title", models.CharField(max_length=190)),
                ("country_name", models.CharField(max_length=120)),
                ("country_flag", models.CharField(max_length=16)),
                ("plan_days", models.PositiveIntegerField()),
                ("plan_data", models.CharField(max_length=32)),
                ("price_usd", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("total_usd", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=store.models.receipt_upload_path,
                        validators=[store.models.validate_receipt_file],
                    ),
                ),
                ("receipt_uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("esim_iccid", models.CharField(blank=True, max_length=64, null=True)),
                ("esim_qr_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "esim_qr_data",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("esim_demo", models.BooleanField(default=False)),
                ("admin_note", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=32, unique=True)),
                ("code", models.CharField(max_length=10)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
