#!/usr/bin/env node
// Generates apps/web/styles/tokens.css from brand/tokens.json.
// tokens.json is the single source of truth for the AVERIX design system; the CSS is a build artifact.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(resolve(root, 'brand/tokens.json'), 'utf8'));

/** Resolves `{violet.600}` references against the palette. */
function deref(value) {
  const m = /^\{([\w-]+)\.([\w-]+)\}$/.exec(String(value));
  if (!m) return value;
  const group = tokens.palette[m[1]];
  if (!group || !(m[2] in group)) throw new Error(`unknown palette reference: ${value}`);
  return group[m[2]];
}

const lines = [];
const out = (s = '') => lines.push(s);

out('/* AVERIX design tokens — GENERATED by scripts/build-tokens.mjs. Do not edit by hand. */');
out('/* Source: brand/tokens.json   Run: npm run tokens */');
out();
out(':root {');
out('  /* ── palette ─────────────────────────────────────────── */');
for (const [group, shades] of Object.entries(tokens.palette)) {
  for (const [shade, hex] of Object.entries(shades)) out(`  --av-${group}-${shade}: ${hex};`);
}
out();
out('  /* ── scale ───────────────────────────────────────────── */');
for (const [k, v] of Object.entries(tokens.space)) out(`  --av-space-${k}: ${v};`);
for (const [k, v] of Object.entries(tokens.radius)) out(`  --av-radius-${k}: ${v};`);
for (const [k, v] of Object.entries(tokens.font)) out(`  --av-font-${k}: ${v};`);
for (const [k, v] of Object.entries(tokens.weight)) out(`  --av-weight-${k}: ${v};`);
for (const [k, v] of Object.entries(tokens.text)) {
  out(`  --av-text-${k}: ${v.size};`);
  out(`  --av-leading-${k}: ${v.line};`);
  out(`  --av-tracking-${k}: ${v.tracking};`);
}
for (const [k, v] of Object.entries(tokens.motion)) out(`  --av-motion-${k}: ${v};`);
for (const [k, v] of Object.entries(tokens.layout)) {
  if (k === 'breakpoints') continue;
  out(`  --av-${k}: ${v};`);
}
for (const [k, v] of Object.entries(tokens.z)) out(`  --av-z-${k}: ${v};`);
out('}');
out();

const themeBlock = (mode) => {
  const body = [];
  for (const [k, v] of Object.entries(tokens.semantic[mode])) body.push(`  --av-${k}: ${deref(v)};`);
  for (const [k, v] of Object.entries(tokens.shadow[mode])) body.push(`  --av-shadow-${k}: ${v};`);
  body.push(`  color-scheme: ${mode};`);
  return body.join('\n');
};

out('/* Light is the default; dark applies on an explicit choice or via the system preference. */');
out(':root {');
out(themeBlock('light'));
out('}');
out();
out(':root[data-theme="dark"] {');
out(themeBlock('dark'));
out('}');
out();
out('@media (prefers-color-scheme: dark) {');
out('  :root:not([data-theme="light"]) {');
out(themeBlock('dark').split('\n').map((l) => '  ' + l).join('\n'));
out('  }');
out('}');
out();

writeFileSync(resolve(root, 'apps/web/styles/tokens.css'), lines.join('\n') + '\n');

// Breakpoints are also needed by JS (device-preview widths, media-query hooks).
const bp = tokens.layout.breakpoints;
writeFileSync(
  resolve(root, 'apps/web/lib/breakpoints.ts'),
  '// GENERATED by scripts/build-tokens.mjs from brand/tokens.json. Do not edit by hand.\n' +
    `export const BREAKPOINTS = ${JSON.stringify(bp, null, 2)} as const;\n\n` +
    'export type Breakpoint = keyof typeof BREAKPOINTS;\n\n' +
    'export const bpPx = (b: Breakpoint): number => parseInt(BREAKPOINTS[b], 10);\n'
);

console.log(`tokens.css written (${lines.length} lines) + lib/breakpoints.ts`);
