#!/usr/bin/env python3
"""Generates services/ai-python/app/taxonomy.py from the reference-data migration.

The analysis service needs the closed set of category and technology slugs so
it can refuse to invent one. Hand-maintaining a second copy of 87 slugs would
drift within a month, so it is generated, and a test in the Python suite fails
if the generated file no longer matches the migration.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MIGRATION = ROOT / "database/migrations/0016_reference_data.up.sql"
OUTPUT = ROOT / "services/ai-python/app/taxonomy.py"


def extract_block(sql: str, table: str) -> str:
    """Returns the text of the first INSERT ... VALUES block for a table."""
    pattern = re.compile(
        rf"INSERT INTO {table}\s*\([^)]*\)\s*VALUES(.*?);", re.DOTALL | re.IGNORECASE
    )
    match = pattern.search(sql)
    if not match:
        raise SystemExit(f"could not find an INSERT INTO {table} block in {MIGRATION.name}")
    return match.group(1)


def first_column_values(block: str) -> list[str]:
    """Returns the first quoted value of every row in a VALUES block."""
    return re.findall(r"\(\s*'([^']+)'", block)


def child_category_slugs(sql: str) -> list[str]:
    """Category slugs from the INSERT ... SELECT blocks that build the tree.

    Those rows come from inline VALUES lists shaped
    ('parent-slug', 'slug', 'Name', 'leaf', order), so the slug is the second
    quoted value rather than the first.
    """
    slugs: list[str] = []
    for block in re.findall(
        r"INSERT INTO categories\s*\([^)]*\)\s*SELECT(.*?);", sql, re.DOTALL | re.IGNORECASE
    ):
        slugs.extend(re.findall(r"\(\s*'[^']+'\s*,\s*'([^']+)'", block))
    return slugs


def main() -> int:
    sql = MIGRATION.read_text(encoding="utf-8")

    specialisations = first_column_values(extract_block(sql, "specialisations"))
    categories = first_column_values(extract_block(sql, "categories")) + child_category_slugs(sql)
    skills = first_column_values(extract_block(sql, "skills"))

    if len(specialisations) < 8:
        raise SystemExit(f"only {len(specialisations)} specialisations found; the parser is wrong")
    if len(categories) < 40:
        raise SystemExit(f"only {len(categories)} categories found; the parser is wrong")
    if len(skills) < 60:
        raise SystemExit(f"only {len(skills)} skills found; the parser is wrong")

    def render(name: str, values: list[str], comment: str) -> str:
        unique = sorted(set(values))
        lines = [f"# {comment}", f"{name}: frozenset[str] = frozenset(", "    {"]
        lines.extend(f'        "{value}",' for value in unique)
        lines.extend(["    }", ")", ""])
        return "\n".join(lines)

    body = [
        '"""The closed AVERIX taxonomy.',
        "",
        "GENERATED by scripts/generate-python-taxonomy.py from",
        "database/migrations/0016_reference_data.up.sql. Do not edit by hand.",
        "",
        "The analysis service uses these to refuse a slug the taxonomy does not",
        'contain: a category or technology the model invented is dropped rather',
        "than stored, because a slug nobody can search for is worse than none.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        render("SPECIALISATION_SLUGS", specialisations, "One primary specialisation per developer."),
        render("CATEGORY_SLUGS", categories, "The project category tree, flattened."),
        render("SKILL_SLUGS", skills, "Every technology the platform knows."),
    ]

    OUTPUT.write_text("\n".join(body), encoding="utf-8")
    print(
        f"wrote {OUTPUT.relative_to(ROOT)}: "
        f"{len(set(specialisations))} specialisations, "
        f"{len(set(categories))} categories, "
        f"{len(set(skills))} technologies"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
